# Generated by Django 4.0.2 on 2022-02-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_dt',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
